[versions]
# libraries
minecraft = "1.8.9"
mappings = "22-1.8.9"
forge = "1.8.9-11.15.1.2318-1.8.9"
devauth = "1.1.2"

# plugins
loom = "0.10.0.+"
loom-pack200 = "0.1.3"
shadow = "8.1.1"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
mappings = { group = "de.oceanlabs.mcp", name = "mcp_stable", version.ref = "mappings" }
devauth = { group = "me.djtheredstoner", name = "DevAuth-forge-legacy", version.ref = "devauth" }
forge = { group = "net.minecraftforge", name = "forge", version.ref = "forge" }
mixin = { group = "org.spongepowered", name = "mixin" }

[plugins]
loom = { id = "gg.essential.loom", version.ref = "loom" }
loom-pack200 = { id = "dev.architectury.architectury-pack200", version.ref = "loom-pack200" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }